name: datn_cntt304_bandogiadung
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.0
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  intl: ^0.17.0
  firebase_core: ^3.6.0
  firebase_storage: ^12.3.3
  provider: ^6.1.2
  image_picker: ^1.1.2
  fl_chart: ^0.65.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: Comfortaa
      fonts:
       - asset: assets/fonts/Comfortaa-Regular.ttf

