name: datn_cntt304_bandogiadung
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.0
  cupertino_icons: ^1.0.8
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/icons/home.svg
    - lib/assets/icons/notification.svg
    - lib/assets/icons/order.svg
    - lib/assets/icons/ic_user.svg
    - lib/assets/icons/bell.png
    - lib/assets/icons/order.png
  fonts:
    - family: Comfortaa
      fonts:
       - asset: lib/assets/fonts/Comfortaa-Regular.ttf


