// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9aZtqix_K3bVum92NMOPzF6wngJ8qkDg',
    appId: '1:730702910807:web:3231604c4aae7b2615da12',
    messagingSenderId: '730702910807',
    projectId: 'cntt304-bansanphamgiadun-10457',
    authDomain: 'cntt304-bansanphamgiadun-10457.firebaseapp.com',
    storageBucket: 'cntt304-bansanphamgiadun-10457.appspot.com',
    measurementId: 'G-BLCWVM9K6J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChj7p1LDzRuSWJkWsHWOALGKB1jzwbvWI',
    appId: '1:730702910807:android:f886c930091bf65215da12',
    messagingSenderId: '730702910807',
    projectId: 'cntt304-bansanphamgiadun-10457',
    storageBucket: 'cntt304-bansanphamgiadun-10457.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRw-R9XcpZT-Tq9hnJvoE3V5Ect3BgKTc',
    appId: '1:730702910807:ios:24e61ac3e06943b315da12',
    messagingSenderId: '730702910807',
    projectId: 'cntt304-bansanphamgiadun-10457',
    storageBucket: 'cntt304-bansanphamgiadun-10457.appspot.com',
    iosBundleId: 'com.example.datnCntt304Bandogiadung',
  );
}
